In [1]:
import pickle as pkl
import numpy as np
import pandas as pd

import matplotlib.pyplot as ptl

In [2]:
expert_states=pkl.load(open("expert_states.pkl", 'rb'))
expert_states

[array([  1, 390]),
 array([  2, 388]),
 array([  3, 385]),
 array([  4, 381]),
 array([  5, 376]),
 array([  6, 370]),
 array([  7, 363]),
 array([  8, 372]),
 array([  9, 380]),
 array([ 10, 387]),
 array([ 11, 393]),
 array([ 12, 398]),
 array([ 13, 402]),
 array([ 14, 405]),
 array([ 15, 407]),
 array([ 16, 408]),
 array([ 17, 417]),
 array([ 18, 425]),
 array([ 19, 432]),
 array([ 20, 438]),
 array([ 21, 443]),
 array([ 22, 447]),
 array([ 23, 450]),
 array([ 24, 452]),
 array([ 25, 453]),
 array([ 26, 453]),
 array([ 27, 462]),
 array([ 28, 470]),
 array([ 29, 477]),
 array([ 30, 483]),
 array([ 31, 488]),
 array([ 32, 492]),
 array([ 33, 495]),
 array([ 34, 497]),
 array([ 35, 498]),
 array([ 36, 498]),
 array([ 37, 497]),
 array([ 38, 495]),
 array([ 39, 492]),
 array([ 40, 488]),
 array([ 41, 483]),
 array([ 42, 477]),
 array([ 43, 470]),
 array([ 44, 462]),
 array([ 45, 453]),
 array([ 46, 443]),
 array([ 47, 452]),
 array([ 48, 460]),
 array([ 49, 467]),
 array([ 50, 473]),


In [5]:
# expert state: ([1, 276], [350, 523])
# state: ([0, 300], [0, 760])
print(len(expert_states))
_min=2000; _max=0
for s in expert_states:
    _min=min(_min, s[1])
    _max=max(_max, s[1])
print(_min, _max)

276
350 523


In [7]:
380*2

760

In [10]:
expert_actions = [2] + pkl.load(open("flappy_ops.pkl", 'rb'))

In [11]:
expert_actions

[2,
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
